run:
  tests: false

output:
  format: colored-line-number

linters:
  enable:
    - bodyclose
    - dupl
    - exportloopref
    - goconst
    - godot
    - goimports
    - goprintffuncname
    - ifshort
    - misspell
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
