version: '3.8'
services:
  tsubaki:
    container_name: tsubaki
    build: .
    restart: always
    depends_on:
      - meilisearch
      - postgres
      - redis
    volumes:
      - type: bind
        source: /opt/arisu/tsubaki/config.yml
        target: ./config.yml
        read_only: true

      - arisu_projects_data:/var/lib/tsubaki/data:rw

  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '5432:5432'
    command: |
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

networks:
  blep:
    driver: app-tier

volumes:
  arisu_postgres_data:
  arisu_projects_data:
  arisu_redis_data:
