name: Deploy to our infrastructure
on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add kubeconfig to runner
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Get release tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Set tag
        run: kubectl set image statefulset/tsubaki tsubaki=arisuland/tsubaki:${{ steps.tag.outputs.tag }}

      - name: Deploy!
        run: kubectl rollout status statefulset/tsubaki
